name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: vfa-khuongdv/homebrew-sys-monitoring
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Get release information
        id: release
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          TARBALL_URL="https://github.com/vfa-khuongdv/sys-monitoring/archive/refs/tags/${TAG_NAME}.tar.gz"
          
          # Download and calculate SHA256
          curl -sL "$TARBALL_URL" | shasum -a 256 | cut -d' ' -f1 > sha256.txt
          SHA256=$(cat sha256.txt)
          
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          echo "tarball_url=${TARBALL_URL}" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          cd homebrew-tap
          
          # Update the formula file
          sed -i \
            -e "s|url \".*\"|url \"${{ steps.release.outputs.tarball_url }}\"|" \
            -e "s|sha256 \".*\"|sha256 \"${{ steps.release.outputs.sha256 }}\"|" \
            Formula/sys-monitoring.rb

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/sys-monitoring.rb
          git commit -m "Update sys-monitoring to ${{ steps.release.outputs.tag_name }}"
          git push
